apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-backend-secrets
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+Mp52QiZGSKGwlMu,iv:KRqpwgze5i9zVWTcneRE+sIq5Xw0/GjK404J4aZfTXg=,tag:jc9JCiewckvoPC1qlp/jzQ==,type:str]
sops:
    age:
        - recipient: age1cx4tzdek3lrfqft09f4enaydt7r07f7rcj5cmn4sxthl0n044d0s2undkx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcFhrQ0VMVXB4Umc4LzVy
            a2t3SmJvY3BneVNlR04xd1B2blJwSVpLSGo4CmRLaDJHVXE3aG1EN0xVV25XblJI
            d1pmRDNSem5ZRGZSQ2wrZEVGcjBMRVUKLS0tIHBxbTltblczbkl6Y0Z6V3VOQ09R
            TS9LMDRwajJjcWVMcTQxRWpQOGhLNzgK/mxnRF5ROzsddlnZXYARguRENPJ9slLk
            C0eNpavzAQ7HfpMcoN047Y91VHYBHnRndqbo6DvNXZ43XTr+xKO9hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T15:25:51Z"
    mac: ENC[AES256_GCM,data:oNzGzTjwd+LAvHXOU/eTGBfqWL1D/CJIQi6GcEHt1HLfYUpT4r9RRvBYmvoXYRGhzTTTVjQci1bjwY9bqOJUFdY+Y/niyyIFtNft4+FqESuqwCuGwTJ5rIf4MCQOJS082Z3ltaZ6VV2rQop4eJPuomH+VXHcgsR+BbhvI+l1fTc=,iv:/tRqD3j5k3ZVXPMNioCxstah9Qln7i0DM3RJmRqzsMI=,tag:Zcp/70JDdqlOOvHTRZs3ew==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
