apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
  - todo-backend/manifests/secret.yaml
  - todo-backend/manifests/postgres.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
