apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: exercises
  name: cpu-rate
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 5m
    successCondition: result < 0.01
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1770-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(
            sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="exercises"})
          )
