apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: ping-pong-secrets
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3L3yklefdf8CbMVu,iv:ZQtdDBxBZJumsu2AARLNYEOuLHwiSbZ+ewz22G3RBx8=,tag:q4jC7VkeUfEHGYPuX9Rslg==,type:str]
sops:
    age:
        - recipient: age1cx4tzdek3lrfqft09f4enaydt7r07f7rcj5cmn4sxthl0n044d0s2undkx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZG1zZmdObzlHMk5remY3
            NEM5cmFMWm4xNjdld0M4VEpYWUV4TVByM1cwCmp1ejVUK1dDc2JodWtqbkl5RnRF
            SDM5UWk2bDhSSktpRktTZ0dSU2ZWUFUKLS0tIDEvOGdXQkJsSmVMYmN4TmVISC81
            U0p3NGZJaW51UHg1aU1PTnpDRFhMaFUKPaPX7mdUc/ELh1KZeCvQPVqL3JkPUlfr
            k5mrqBtkkycAI7qSufj1agvqoDop4rXR9sHjGAGzn3p6aKMZQpChBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T21:34:24Z"
    mac: ENC[AES256_GCM,data:qtJdbXqYQQB/vwwO20hBTQH2Fj4v8PMFHxIkfZPUqIiJdvBJ6+wqJv7a2W2Tz1jTqeO7uZqHyps3f3yl8D46BV75RLteOL5SMNDCwwcVALjIdL16ahtllfSwrbfKU8PSvOTs5np11QiLtB16rCUD1KUh7PlFcuA3iQyXwfV8nNs=,iv:YypDqnToQXjpI0UKqqOlpsUjqZVivJ9cB8xXcaCjcGM=,tag:aUXs49g2VrMNRcGGoRFpZw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
