apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: log-claim
        - name: config
          configMap:
            name: log-output-conf
            items:
              - key: "information.txt"
                path: "information.txt"
      containers:
        - name: log-output
          image: log-output
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-files
              mountPath: /app/files
        - name: log-reader
          image: log-reader
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: PINGS_URL
              value: "http://ping-pong-svc:2345/pings"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-conf
                  key: message
          volumeMounts:
            - name: shared-files
              mountPath: /app/files
            - name: config
              mountPath: /app/config
              readOnly: true
